version: '3.7'
services:
  nginx:
    image: ghcr.io/victorposada/website:latest
    pull_policy: always
    container_name: website
    restart: always
    networks:
      - localhost
    ports:
      - 80:80
      - 443:443

  prometheus:
    image: prom/prometheus:v2.45.2
    user: root
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus/data:/prometheus
    container_name: prometheus
    restart: always
    networks:
      - localhost
    ports:
      - 9090:9090

  nginx-prometheus-exporter:
    image: nginx/nginx-prometheus-exporter:1.0
    container_name: prometheus-nginx-exporter
    restart: always
    command:
      - -nginx.scrape-uri=http://website/stub_status
    expose: 
      - 9113
    networks:
      - localhost
    depends_on:
      - prometheus

  prometheus-node-exporter:
    image: prom/node-exporter:v1.7.0
    container_name: prometheus-node-exporter
    restart: always
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command: 
      - '--path.procfs=/host/proc' 
      - '--path.sysfs=/host/sys'
      - --collector.filesystem.ignored-mount-points
      - "^/(sys|proc|dev|host|etc|rootfs/var/lib/docker/containers|rootfs/var/lib/docker/overlay2|rootfs/run/docker/netns|rootfs/var/lib/docker/aufs)($$|/)"
    networks:
      - localhost
    privileged: true
    depends_on:
      - prometheus
    expose:
      - 9100

  grafana:
    image: grafana/grafana:10.0.10
    container_name: grafana
    restart: always
    depends_on:
      - prometheus
    volumes:
      - ./grafana/data:/var/lib/grafana
    networks:
      - localhost
    ports:
      - 3000:3000
    user: root
    environment:
      - GF_SECURITY_ADMIN_USER=user
      - GF_SECURITY_ADMIN_PASSWORD=password
  
networks:
    localhost:
        name: localhost
        external: false